version: '3'
services:
  redirect-server:
    build: .
    ports:
      - "80:80"
    environment:
      - TARGET_URLS=https://example.com,https://duckduckgo.com
      - URLS_LIST=https://api.invidious.io
